---
- hosts: "{{ aminode }}"
  roles:
    - magma-agw-1.4
  vars:
    ansible_ssh_private_key_file: "{{ dirInventory }}/{{ keyHost }}.pem"
  vars_files:
    - roles/vars/defaults.yaml
    - "{{ dirInventory }}/secrets.yaml"
    - roles/vars/cluster.yaml
