---

- hosts: localhost
  roles:
    - aws-cleanup 
  vars_files:
    - roles/vars/cluster.yaml
    - roles/vars/defaults.yaml
    - "{{ dirInventory }}/secrets.yaml"
  environment:
    AWS_ACCESS_KEY_ID: "{{ awsAccessKey }}"
    AWS_SECRET_ACCESS_KEY: "{{ awsSecretKey }}"


