---

- hosts: "{{ devops }}"
  roles:
    - { role: ansible-server, become: yes }
    - golang-host
    - mantle-base
    - build-platform
    - { role: key-manager, tags: keyManager }     
  vars_files:
    - roles/vars/defaults.yaml
    - roles/vars/cluster.yaml
    - roles/vars/build.yaml
    - "{{ dirLocalInventory }}/secrets.yaml"
  vars:
    ansible_ssh_private_key_file: "{{ dirLocalInventory }}/{{ keyHost }}.pem"
