---
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

log_level: INFO

# Interface for internal packet sending
interface_name: li_port

# Used for generated internal packets
pkt_dst_mac: "11:99:99:bb:aa:a3"
pkt_src_mac: "99:11:44:31:ff:ff"

proxy_addr: "127.0.0.1"
proxy_port: 5555
cert_file: "/tmp/domain.crt"
key_file: "/tmp/domain.key"
