---

- name: locate VPC
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ orc8rVpc }}"
  register: valVpc


- name: set vpc cidr fact
  set_fact: 
    factVpcCidr: "{{ valVpc.vpcs[0].cidr_block }}"

- name: set vpc id fact
  set_fact: 
    factVpcId: "{{ valVpc.vpcs[0].vpc_id }}"

- name: delete vpc
  ec2_vpc_net:
    state: absent
    name: "{{ orc8rVpc }}"
    cidr_block: "{{ factVpcCidr }}"
  tags: tagDeleteVpc
