---

#TODO: presumes helm14 directory is available on github. use gh to check and create
#

- name: publish helm charts
  command: "/usr/bin/bash package.sh -d {{ buildDeploymentType }} "
  args:
    chdir: "{{ buildPackageDir }}"

- name: verify helm charts
  script: "roles/build-platform/files/helm-verify.bash {{ gitUser }} {{ gitPat }} {{ buildHelmRepo }}" 

