---

#TODO: presumes magma-helm directory is available on github
#

- name: clear existing directories
  file: 
    path: "{{ magmaHelmDir }}"
    state: absent

- name: create new chart directory
  file: 
    path: "{{ magmaHelmDir }}"
    state: directory
    mode: '0755'

- name: publish helm charts
  script: "roles/build-platform/files/helm-publish.bash {{ gitUser }} {{ gitPat }} {{ buildHelmRepo }} {{ dirSourceLocal }}"

- name: verify helm charts
  script: "roles/build-platform/files/helm-verify.bash {{ gitUser }} {{ gitPat }} {{ buildHelmRepo }}" 

