
---
swagger: '2.0'

info:
  title: Session Manager definitions
  description: These events occur in session_manager
  version: 1.0.0

definitions:
  session_created:
    type: object
    description: Used to track when a session was created
    properties:
      imsi:
        type: string
      ip_addr:
        type: string
      msisdn:
        type: string
      imei:
        type: string
      spgw_ip:
        type: string
      session_id:
        type: string
      apn:
        type: string
      mac_addr:
        type: string
      pdp_start_time:
        type: integer
  session_create_failure:
    type: object
    description: Used to track when a session creation failed
    properties:
      imsi:
        type: string
      apn:
        type: string
      mac_addr:
        type: string
      failure_reason:
        type: string
  session_updated:
    type: object
    description: Used to track when a session update is reported
    properties:
      imsi:
        type: string
      apn:
        type: string
      mac_addr:
        type: string
      ip_addr:
        type: string
  session_update_failure:
    type: object
    description: Used to track when a session update has failed
    properties:
      imsi:
        type: string
      apn:
        type: string
      mac_addr:
        type: string
      ip_addr:
        type: string
      failure_reason:
        type: string
  session_terminated:
    type: object
    description: Used to track total session metrics
    properties:
      imsi:
        type: string
      apn:
        type: string
      mac_addr:
        type: string
      ip_addr:
        type: string
      msisdn:
        type: string
      imei:
        type: string
      spgw_ip:
        type: string
      session_id:
        type: string
      total_tx:
        type: integer
        minimum: 0
      total_rx:
        type: integer
        minimum: 0
      charging_tx:
        type: integer
        minimum: 0
      charging_rx:
        type: integer
        minimum: 0
      monitoring_tx:
        type: integer
        minimum: 0
      monitoring_rx:
        type: integer
        minimum: 0
      pdp_start_time:
        type: integer
      pdp_end_time:
        type: integer
