- name: Check if we have atleast 3 availability zones in our deployment
  amazon.aws.aws_az_info:
  register: aws_az_info
  failed_when: aws_az_info.availability_zones | length < 3
  tags:
    - install_precheck
    - upgrade_precheck

- name: Debug availability zones present in our region
  amazon.aws.aws_az_info:
  register: aws_az_info
  failed_when: aws_az_info.availability_zones | length < 3
  tags:
    - install_precheck
    - upgrade_precheck