---
- name: provision edge networks
  cloudformation:
    stack_name: "stack{{ siteName }}Network"
    state: "present"
    template: "roles/cfn/cfnMagmaEdgeNetPublic.json"
    template_parameters:
      paramCidr: "{{ cidrVpc }}"
      paramSgiCidr: "{{ cidrSgi }}"
      paramEnbCidr: "{{ cidrEnodeb }}"
      paramAvlZone: "{{ awsAgwAz }}"
      paramSecGroupName: "{{ secGroup }}{{ siteName }}"
      paramSgiSubnetTagName: "{{ siteName }}-SgiSubnet"
      paramEnodebSubnetTagName: "{{ siteName }}-EnodebSubnet"
      paramRouteTableTagName: "{{ siteName }}-RouteTable"
      paramGwTagName: "{{ siteName }}-InternetGateway"
      paramVpcTagName: "{{ siteName }}-VPC"

