---

- name: identify sgi subnet id using tag
  ec2_vpc_subnet_info:  
    filters:
      "tag:Name": "{{ siteName }}-SgiSubnet"
  register: valSgiSubnet

- name: set sgi subnet fact
  set_fact:
    factSgiSubnetId: "{{ valSgiSubnet.subnets[0].subnet_id }}"

- name: identify security group using tag, of the form sitename-secgroup
  ec2_group_info:
    filters:
      group-name: "{{ secGroup }}{{ siteName }}"
  register: valSecGroup

- name: set security group fact
  set_fact:
    factSecGroup: "{{ valSecGroup.security_groups[0].group_id }}"


- name: provision agw base
  cloudformation:
    stack_name: "stack{{ siteName }}{{ idAgw }}"
    state: present
    template: "roles/cfn/cfnMagmaAgwPublic.json"
    template_parameters:
      paramImageBase: "{{ imageDebianAgw }}"
      paramSubnetSgi: "{{ factSgiSubnetId }}"
      paramAzHome: "{{ awsAgwAz }}"
      paramSecGroup: "{{ factSecGroup }}"
      paramSshKey: "{{ sshKeyAgw }}"
      paramAgwTagName: "{{ siteName }}{{ idAgw }}"
